### PR TITLE
Moved Sanity to /app and removed /pages

### LINKED ISSUE #4: Move to Nextjs app router

### PR DESCRIPTION
**Pull request by madisonbullard**

### CODE REVIEW

**Comment by madisonbullard** [comment]
@daltn not sure why the netlify checks are failing... it runs fine locally and the build is successful 🤔 

any ideas?

**Comment by daltn** [comment]
> @daltn not sure why the netlify checks are failing... it runs fine locally and the build is successful 🤔
> 
> any ideas?

Seems to not be finding the build directory? Here's the log:

```
9:36:52 PM: Waiting for other deploys from your team to complete. Check the queue: https://app.netlify.com/teams/daltn/builds
9:38:01 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
9:37:14 PM: build-image version: c11c0eb9939c949586b0f78302107908b668a11e (focal)
9:37:14 PM: buildbot version: c11c0eb9939c949586b0f78302107908b668a11e
9:37:14 PM: Fetching cached dependencies
9:37:14 PM: Starting to download cache of 1.1GB
9:37:20 PM: Finished downloading cache in 5.891s
9:37:20 PM: Starting to extract cache
9:37:26 PM: Finished extracting cache in 6.485s
9:37:26 PM: Finished fetching cache in 12.494s
9:37:26 PM: Starting to prepare the repo for build
9:37:26 PM: Preparing Git Reference pull/17/head
9:37:28 PM: Starting to install dependencies
9:37:28 PM: Python version set to 3.8
9:37:28 PM: Attempting Ruby version 2.7.2, read from environment
9:37:29 PM: Using Ruby version 2.7.2
9:37:29 PM: Started restoring cached go cache
9:37:29 PM: Finished restoring cached go cache
9:37:30 PM: go version go1.19.10 linux/amd64
9:37:30 PM: Using PHP version 8.0
9:37:31 PM: Started restoring cached Node.js version
9:37:32 PM: Finished restoring cached Node.js version
9:37:32 PM: v18.16.1 is already installed.
9:37:32 PM: Now using node v18.16.1 (npm v9.5.1)
9:37:33 PM: Enabling Node.js Corepack
9:37:33 PM: Started restoring cached build plugins
9:37:33 PM: Finished restoring cached build plugins
9:37:33 PM: Started restoring cached corepack dependencies
9:37:33 PM: Finished restoring cached corepack dependencies
9:37:33 PM: No npm workspaces detected
9:37:33 PM: Started restoring cached node modules
9:37:33 PM: Finished restoring cached node modules
9:37:33 PM: Installing npm packages using npm version 9.5.1
9:37:34 PM: up to date, audited 974 packages in 1s
9:37:34 PM: 188 packages are looking for funding
9:37:34 PM:   run `npm fund` for details
9:37:34 PM: found 0 vulnerabilities
9:37:34 PM: npm packages installed
9:37:35 PM: Install dependencies script success
9:37:35 PM: Starting build script
9:37:36 PM: Detected 1 framework(s)
9:37:36 PM: next at version 13.4.4
9:37:36 PM: Section completed: initializing
9:37:37 PM: ​
9:37:37 PM: Netlify Build                                                 
9:37:37 PM: ────────────────────────────────────────────────────────────────
9:37:37 PM: ​
9:37:37 PM: ❯ Version
9:37:37 PM:   @netlify/build 29.12.1
9:37:37 PM: ​
9:37:37 PM: ❯ Flags
9:37:37 PM:   baseRelDir: true
9:37:37 PM:   buildId: 64925434055fd900087df407
9:37:37 PM:   deployId: 64925434055fd900087df409
9:37:37 PM: ​
9:37:37 PM: ❯ Current directory
9:37:37 PM:   /opt/build/repo
9:37:37 PM: ​
9:37:37 PM: ❯ Config file
9:37:37 PM:   /opt/build/repo/netlify.toml
9:37:37 PM: ​
9:37:37 PM: ❯ Context
9:37:37 PM:   deploy-preview
9:37:37 PM: ​
9:37:37 PM: ❯ Using Next.js Runtime - v4.38.0
9:37:38 PM: ​
9:37:38 PM: @netlify/plugin-nextjs (onPreBuild event)                     
9:37:38 PM: ────────────────────────────────────────────────────────────────
9:37:38 PM: ​
9:37:38 PM: Next.js cache restored.
9:37:38 PM: Netlify configuration property build.environment.NEXT_PRIVATE_TARGET value changed.
9:37:38 PM: ​
9:37:38 PM: (@netlify/plugin-nextjs onPreBuild completed in 141ms)
9:37:38 PM: ​
9:37:38 PM: Build command from Netlify app                                
9:37:38 PM: ────────────────────────────────────────────────────────────────
9:37:38 PM: ​
9:37:38 PM: $ npm run build
9:37:39 PM: > build
9:37:39 PM: > next build
9:37:39 PM: - info Creating an optimized production build...
9:37:58 PM: - info Compiled successfully
9:37:58 PM: - info Linting and checking validity of types...
9:37:59 PM: Pages directory cannot be found at /opt/build/repo/pages or /opt/build/repo/src/pages. If using a custom path, please configure with the `no-html-link-for-pages` rule in your eslint config file.
9:38:00 PM: Failed to compile.
9:38:00 PM: 
9:38:00 PM: app/api/exit-preview/route.ts
9:38:00 PM: Type error: Route app/api/exit-preview/route.ts does not match the required types of a Next.js Route.
9:38:00 PM:   GET is not a valid Route export field.
9:38:00 PM: ​
9:38:00 PM: build.command failed                                        
9:38:00 PM: ────────────────────────────────────────────────────────────────
9:38:00 PM: ​
9:38:00 PM:   Error message
9:38:00 PM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
9:38:00 PM: ​
9:38:00 PM:   Error location
9:38:00 PM:   In Build command from Netlify app:
9:38:00 PM:   npm run build
9:38:00 PM: ​
9:38:00 PM:   Resolved config
9:38:00 PM:   build:
9:38:00 PM:     command: npm run build
9:38:00 PM:     commandOrigin: ui
9:38:00 PM:     environment:
9:38:00 PM:       - NEXT_PUBLIC_SANITY_DATASET
9:38:00 PM:       - NEXT_PUBLIC_SANITY_PROJECT_ID
9:38:00 PM:       - REVIEW_ID
9:38:00 PM:       - SANITY_API_DATASET
9:38:00 PM:       - SANITY_API_PROJECT_ID
9:38:00 PM:       - SANITY_API_READ_TOKEN
9:38:00 PM:       - SANITY_API_WRITE_TOKEN
9:38:00 PM:       - SANITY_STUDIO_DATASET
9:38:00 PM:       - SANITY_STUDIO_PROJECT_ID
9:38:00 PM:       - NEXT_PRIVATE_TARGET
9:38:00 PM:     publish: /opt/build/repo/.next
9:38:00 PM:     publishOrigin: ui
9:38:00 PM:   plugins:
9:38:00 PM:     - inputs: {}
9:38:00 PM:       origin: ui
9:38:00 PM:       package: '@netlify/plugin-nextjs'
9:38:01 PM: Caching artifacts
9:38:01 PM: Started saving node modules
9:38:01 PM: Finished saving node modules
9:38:01 PM: Started saving build plugins
9:38:01 PM: Finished saving build plugins
9:38:01 PM: Started saving corepack cache
9:38:01 PM: Finished saving corepack cache
9:38:01 PM: Started saving pip cache
9:38:01 PM: Finished saving pip cache
9:38:01 PM: Started saving emacs cask dependencies
9:38:01 PM: Finished saving emacs cask dependencies
9:38:01 PM: Started saving maven dependencies
9:38:01 PM: Finished saving maven dependencies
9:38:01 PM: Started saving boot dependencies
9:38:01 PM: Finished saving boot dependencies
9:38:01 PM: Started saving rust rustup cache
9:38:01 PM: Finished saving rust rustup cache
9:38:01 PM: Started saving go dependencies
9:38:01 PM: Finished saving go dependencies
9:38:01 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
9:38:01 PM: Failing build: Failed to build site
9:38:01 PM: Finished processing build request in 47.537s
```

**Comment by madisonbullard** [comment]
@daltn fixed

**Comment by daltn** [comment]
thanks!! all this config work you've been doing has been huge

**Review by daltn — APPROVED** [review]

**Pull request merged**
